centos (almost)
This mostly works. If you build and run the image, you can use the nix
package manager, e.g.

  cd centos
  docker build --tag nix-centos .

  docker run -it --rm --name nix-centos nix-centos
  [fnord@dc0eecb459d6 ~]$ nix-env --install --attr man
  installing 'man-db-2.7.5'
  ...
  created 74 symlinks in user environment

However, attempting to update the channel fails due to some ssl ca-cert
stuff, thus the commented out nix-channel `--add` and `--update`
commands. Uncommenting them results in the following error during the
`docker build`:

  error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': Problem with the SSL CA cert (path? access rights?) (77)

I think the solution is somewhere in this issue, but haven't gotten it
sorted out yet: https://github.com/NixOS/nix/issues/2008

Possibly related, attempting to install packages via nix-env directly in
the Dockerfile hangs. I've commented out the "Install desired packages"
section of the Dockerfile, so this isn't currently blocking anything,
but I'm hoping the hanging is related to the above ssl issue. I did not
experience such behavior in the alpine-based image.